{{- if and .Values.ruler.enabled .Values.ruler.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" . }}-ruler
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: receive
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
    kind: StatefulSet
    name: {{ include "common.names.fullname" . }}-ruler
  minReplicas: {{ .Values.ruler.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ruler.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.ruler.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.ruler.autoscaling.targetMemory  }}
    {{- end }}
    {{- if .Values.ruler.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.ruler.autoscaling.targetCPU }}
    {{- end }}
{{- end }}
