apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  defaultBackend:
    service:
      name: {{ .Chart.Name }}
      port:
        number: {{ .Values.service.targetPort }} 
