apiVersion: v1
kind: Service
metadata:
  name: {{  .Chart.Name }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'    
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}  
  ports:
  - port: {{ .Values.service.httpPort }}
    protocol: TCP
    name: http