name: Go

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      
    - name: Check out code
      uses: actions/checkout@v2
        
    - name: Extract Git Tag
      run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
 
    - name: Login to Digitalocean
      uses: docker/login-action@v1
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}


    - name: Build and push image to digitalocean
      run: |
        cd 'ArgoCD Image Updater'
        docker build -t registry.digitalocean.com/tanmaybhat/test-app:${{ env.GIT_TAG }} .
        docker push registry.digitalocean.com/tanmaybhat/test-app:${{ env.GIT_TAG }}      
